# Generated by Django 6.0.1 on 2026-01-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inCart',
            field=models.BooleanField(default=False),
        ),
    ]
