# Generated by Django 6.0.1 on 2026-02-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='inCart',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
